FROM node:18-alpine AS base

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

FROM node:18-alpine AS runner

ENV NODE_ENV production
ENV PORT 3000

EXPOSE 3000

# Copy the build output and node_modules from the previous stage
WORKDIR /app
COPY --from=base /app/next.config.js ./
COPY --from=base /app/public ./public
COPY --from=base /app/.next ./.next
COPY --from=base /app/node_modules ./node_modules
COPY --from=base /app/package.json ./

CMD ["npm", "run", "start"]
